from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR/'data'
RAW_DATA_DIR = DATA_DIR/'raw'
ANNOTATION_DIR = DATA_DIR/'annotations'
MASK_DIR = DATA_DIR/'masks'

BATCH_SIZE = 2
EPOCHS = 50
LR = 3e-4
VAL_SPLIT = 0.25
SEED = 42

PATIENCE = 15
GRAD_CLIP = 1.0
NUM_WORKERS = 4
MIN_TUMOR_PIXELS = 10

WARMUP_EPOCHS = 5
COSINE_EPOCHS = 45

IMG_SIZE = 256
BG_RATIO = 2

# Training settings
REMOVE_EMPTY_SLICES = True
BCE_WEIGHT = 0.5
DICE_WEIGHT = 0.5